Resources:
  BetsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: betId
          AttributeType: S
        - AttributeName: betStatus
          AttributeType: S
      KeySchema:
        - AttributeName: betId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: BetStatusIndex
          KeySchema:
            - AttributeName: betStatus
              KeyType: HASH
          Projection:
            ProjectionType: 'ALL'
      BillingMode: PAY_PER_REQUEST
